version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore dotnetLexChatBot/dotnetLexChatBot.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output dotnetLexChatBot/dotnetLexChatBot.csproj
artifacts:
  files:
    - dotnetLexChatBot/build_output/**/*
    - scripts/**/*
    - appspec.yml
