#!/bin/bash
cd /home/ubuntu/

# install dotnet core
# https://www.microsoft.com/net/core#linuxubuntu
if [ ! -f /usr/bin/dotnet ]; then
    echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
    apt-get update

    apt-get install dotnet-dev-1.0.4 -y
fi

# first time running dotnet tool requires setting up package cache
dotnet nuget
